name: Deploy to NGINX server

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      pull-requests: read
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy src/ to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'src/*'
          target: '/var/www/html'
          strip_components: 1
          rm: true
